import type { PlayerSettings } from './Settings.js';
import {qualityDescription} from './RenderQuality.js';

export function settingsPanel(settings: PlayerSettings) {
  const slider = (id: string, label: string, value: number, max = 100) => `<label class="setting-row" for="${id}"><span>${label}</span><output data-value-for="${id}">${value}${max === 100 ? '%' : ''}</output><input id="${id}" type="range" min="${max === 10 ? 1 : 0}" max="${max}" value="${value}"/></label>`;
  return `<h2>USTAWIENIA</h2><p class="settings-intro">Dopasuj sterowanie i dźwięk. Zmiany zapisują się automatycznie.</p>
    <div class="settings-grid"><section class="settings-section"><h3>01 / STEROWANIE</h3>${slider('sensitivity', 'Czułość myszy', settings.sensitivity, 10)}<p>WASD — ruch · SHIFT — sprint<br>SPACJA — skok · R — przeładuj<br>1–6 — broń · ESC — pauza<br>1 nóż · 2 pistolet · 3 PM · 4 karabin · 5 snajperka · 6 strzelba. W meczu tylko posiadana broń.</p><label for="crosshair-color">Kolor celownika</label><select id="crosshair-color"><option value="#ffffff">Biały</option><option value="#64e9d6">Miętowy</option><option value="#ffd166">Złoty</option></select><label for="crosshair-size">Rozmiar celownika</label><input id="crosshair-size" type="range" min="20" max="48" value="${settings.crosshairSize}"/><div id="crosshair-preview" aria-label="Podgląd celownika">+</div></section>
    <section class="settings-section"><h3>02 / DŹWIĘK</h3>${slider('volume', 'Głośność główna', settings.volume)}${slider('music-volume', 'Muzyka', settings.musicVolume)}${slider('effects-volume', 'Efekty', settings.effectsVolume)}<button id="test-audio">SPRAWDŹ DŹWIĘK</button></section>
    <section class="settings-section"><h3>03 / OBRAZ</h3><label for="quality">Jakość renderowania</label><select id="quality" aria-describedby="quality-description"><option value="low">Niska — większa płynność</option><option value="medium">Średnia — zrównoważona</option><option value="high">Wysoka — ostrzejszy obraz</option></select><p id="quality-description" role="status">${qualityDescription[settings.quality]}</p><p>Zmiana nie wpływa na kolizje ani widoczność przeciwników.</p></section>
    <section class="settings-section"><h3>04 / KONTO</h3><button id="show-account-code">POKAŻ KOD KONTA</button><input id="restore-account" aria-label="Kod konta" placeholder="WKLEJ KOD KONTA"/><button id="restore-account-button">PRZYWRÓĆ KONTO</button><p id="account-status" role="status"></p></section></div>`;
}
